Fix compilation error caused by SwiftPrometheus API change
```
/Users/ylee/apple/swift-distributed-actors/Samples/SampleMetrics/main.swift:83:23: error: ambiguous reference to member 'collect'
                print(prom.collect())
                      ^~~~
Prometheus.PrometheusClient:3:17: note: found this candidate
    public func collect(_ succeed: (String) -> ())
                ^
Prometheus.PrometheusClient:4:17: note: found this candidate
    public func collect(into promise: NIO.EventLoopPromise<String>)
                ^
Prometheus.PrometheusClient:5:17: note: found this candidate
    public func collect(_ succeed: (NIO.ByteBuffer) -> ())
                ^
Prometheus.PrometheusClient:6:17: note: found this candidate
    public func collect(into promise: NIO.EventLoopPromise<NIO.ByteBuffer>)
```

Copied from https://github.com/apple/swift-distributed-actors/pull/40/commits/ac32225281010df23a583c50137fb451d2e7bc65