Fix copyright header in protobuf files (#49)
* Fix compilation error caused by SwiftPrometheus API change

```
/Users/ylee/apple/swift-distributed-actors/Samples/SampleMetrics/main.swift:83:23: error: ambiguous reference to member 'collect'
                print(prom.collect())
                      ^~~~
Prometheus.PrometheusClient:3:17: note: found this candidate
    public func collect(_ succeed: (String) -> ())
                ^
Prometheus.PrometheusClient:4:17: note: found this candidate
    public func collect(into promise: NIO.EventLoopPromise<String>)
                ^
Prometheus.PrometheusClient:5:17: note: found this candidate
    public func collect(_ succeed: (NIO.ByteBuffer) -> ())
                ^
Prometheus.PrometheusClient:6:17: note: found this candidate
    public func collect(into promise: NIO.EventLoopPromise<NIO.ByteBuffer>)
```

Copied from https://github.com/apple/swift-distributed-actors/pull/40/commits/ac32225281010df23a583c50137fb451d2e7bc65

* Fix copyright header in protobuf files

Motivation:
The generated `.pb.swift` files have two headers. One is:

```
// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Cluster/SWIM/SWIM.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/
```

Currently it is missing.

The other is copyright header copied from source `.proto` file. Some of the `.proto` files don't have correct year(s).

Modifications:
Fix copyright header in `.proto` files and regenerate `.pb.swift` files.

Result:
Correct copyright header in `.proto` and `.pb.swift` files.

* Update license header validation to exclude .pb.swift files

Motivation:
`validate_license_header.sh` fails with:

```
=> Checking license headers
   * swift-or-c... missing headers in file './Sources/DistributedActorsBenchmarks/Protobuf/bench.pb.swift'!
```

Because `.pb.swift` files have the additional "DO NOT EDIT..." header at the top.

Modifications:
Exclude `.pb.swift` files from license header validation. As long as their source `.proto` files contain the appropriate copyright header, the generated `.pb.swift` will have it as well.

Results:
`validate_license_header.sh` passes.