(Almost...) Refactoring towards SWIM.Instance containing logic and Shell driving it
* WIP on making the SWIM.Instance contain all logic and the shell be interpreting,
rather than the logic be spread through the shells body; also less
boilerplate and some renamings to keep names understandabler

* WIP

* eaning up after rebase

* test fixes

* fixed suspects

* -log apple/swift-log already handles printing metadata

* Finished large refactoring, all tests pass

* neables tracelogging all messages that SWIM uses

* fix how call site errors are printed inside an eventually block

* cleanup

* still working; refactoring mark to have _one_ way to do it

* localShellPath is not needed, we introduce "myself" as a concept

* =swim resolve potential(?) bug in marking node as alive from ping-req

* Pull reacting to onPing into SWIM.Instance and add more tests

* =ask,fix Fix broken ask test during refactorings (error contains now timeout)

* fix test_suspendedActor_shouldBeUnsuspendedOnFailedResumeSystemMessage

Failure was due to pretty printing call site failures:

```
        try p.expectMessage().shouldStartWith(prefix:
"unsuspended:CallSiteError")
                             ^~~~~~~~~~~~~~~~
error: Expected [unsuspended:error(message: "\n
ref.sendSystemMessage(.resume(.failure(ExecutionError(underlying:
testKit.error()))))\n
\u{1B}[0;31m^~~~~~\nerror: <no message>\u{1B}[0;0m")] to start with
prefix:
                [unsuspended:CallSiteError]. (Matching sub-prefix marked
in bold)
```

* =swim Ensure that pinged==pingedMember when receiving pingReqResult;

fix wrong test

* test_swim_shouldConvergeStateThroughGossip is happy

* onPing cleanups

* Implement notMyself more efficiently

* =swim fix test, the node in the memberlist is a remote one

* metadata sorting to be done in other PR

* seems to break CI, on old Swift?

```
            throw
CodingError.missingActorSerializationContext(SWIM.Member.self, details:
"While decoding [\(Self.self)], using [\(decoder)]")
                                                                                                             ^~~~
```

* =swim revert to the membersToPing mutating implementation, document that
it is a swim extension

* =swim swim.member properly handling myself (the "owning shell" ref)

* remove "from future ping" test

* remove not used for testing var

* addressed all remaining review things (i think)

* remove needless passing of payload, log warning "weird" ping message